# Shell variables
# Generated by 'wal'
wallpaper='/home/ishan/Pictures/wallpapers/Courtside-Sunset.png'

# Special
background='#0a0909'
foreground='#b5aeb7'
cursor='#b5aeb7'

# Colors
color0='#0a0909'
color1='#324A70'
color2='#5C536B'
color3='#A8502A'
color4='#9F5E63'
color5='#E1675B'
color6='#ED9265'
color7='#b5aeb7'
color8='#7e7980'
color9='#324A70'
color10='#5C536B'
color11='#A8502A'
color12='#9F5E63'
color13='#E1675B'
color14='#ED9265'
color15='#b5aeb7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
